config/routes.rb
Rails.application.routes.draw do
   get '/articles/autocomplete' => 'articles#autocomplete'

  resources :tags
 
  resources :articles do
   resources :comments
 end
  devise_for :authors, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root 'articles#index'
   get 'author_profile/:id' => 'articles#author_profile', as: :author_profile
   get '/name' => 'articles#name' ,as: :name

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :author
  belongs_to :article
  
  validates :body, :presence => true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :check, only: [:edit]

  # GET /comments
  # GET /comments.json
  # def index
  #   @comments = Comment.all
  # end

  # GET /comments/1
  # GET /comments/1.json
  # def show
  # end

  # GET /comments/new
  # def new
  #   @comment = Comment.new
  #   @article= Article.find(params[:article_id])
  # end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
    @article = Article.find(params[:article_id])
    # @comment.article_id = params[:article_id]
    respond_to do |format|
    format.js {render :layout => false} 
    end

    # respond_to do |format|
    # format.html { redirect_to article_comment_path(:article_id => @comment.article.id, :id => @comment.id) }
  end
 # format.js
#        
#       if params[:@xyz].present?

#         respond_to do |format|
#         format.js {render :layout => false} 
#       end
# else
#         respond_to do |format|
#         # format.html { redirect_to article_comment_path(:article_id => @comment.article.id, :id => @comment.id) }
#         # format.js
#         end


#         end




  # POST /comments
  # POST /comments.json
  def create

    @comment = Comment.new(comment_params)
    @article= Article.find(params[:article_id])
    @comment.article_id = params[:article_id]
   
    @comm=Comment.where(:article_id => params[:article_id])
   @c = @comm.count
    respond_to do |format|
      if @comment.save
       format.js
     end
   end
    # respond_to do |format|
    #   if @comment.save
    #     format.html { redirect_to article_path(@article.id), notice: 'Comment was successfully created.' }
    #     format.json { render :show, status: :created, location: @article }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @article.errors, status: :unprocessable_entity }
    #   end
    # end
  end

     # redirect_to article_path(@comment.article_id)
       # respond_to do |format|
       #  if @comment.save
       #        format.js
       #          end
       #    end 



  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update

     @comment = Comment.find(params[:id])
     @article= Article.find(params[:article_id])
      # @comment.article_id = params[:article_id]

      @comment.update(comment_params)
      respond_to do |format|

           format.js
      #   format.html { redirect_to article_path(@comment.article.id), notice: 'Comment was successfully updated.' }
      #   format.json { render :show, status: :ok, location: @article }
      # else
      #   format.html { render :edit }
      #   format.json { render json: @article.errors, status: :unprocessable_entity }
    
    end

  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
   @author= Author.find(current_author.id)
   @comment = Comment.find(params[:id])
   @article = Article.find(params[:article_id])
   @comment_id = @comment.id
   if @comment.destroy
    respond_to do|format|
      format.js
    end


    # respond_to do |format|
    #   format.html { redirect_to article_path(@comment.article_id), notice: 'Comment was successfully destroyed.' }
    #   format.json { head :no_content }


  end
end

def check
  @comment = Comment.find(params[:id])
  if current_author.id!=@comment.author_id
   respond_to do |format|
     format.html { redirect_to articles_path, notice: 'You are not authorised.' }
     format.json { render :show, status: :ok, location: @comment }
   end
 end
end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :author_id, :article_id)
    end
  end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_editform.html.erb
<div class="hide-form">
<div class="comment comment-box">
 <div class="user-photo">
 <%= link_to (image_tag current_author.author_pic.url(:small), :class=>"show-user-comment-pic"), author_profile_path(current_author.id) %>

 </div>
<div class="comment-body">
<%= form_for [ @article, @comment ], :remote=>"true" do |f|%>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
                <div class="input-group">
                  <div class="inputer">
                    <div class="input-wrapper">
               
                            <%= f.text_area :body, :placeholder=> "Join the discussion", :class=>"form-control js-auto-size", :rows=>"1", :required => "true", :id=>"edit-comment-x", :style=>"overflow:hidden;" %>
                     
                    </div>
                  </div><!--.inputer-->
  <div class="field">
    
    <%= f.hidden_field :author_id, :value => current_author.id %>
  </div>
  <div class="field">
    
    <%= f.hidden_field :article_id, :value => @article.id %>
  </div>

                  <span class="input-group-btn">
                    <%= f.submit "Send", :class=>"btn btn-primary btn-ripple" %>
                  </span>
                </div><!--.input-group-->

              </div><!--.comment-body-->





<% end %>

  </div><!--.comment-->
</div>

<script type="text/javascript">
 
  $(".edit-comment-btn").click(function(){
       $(".hide-form").each(function(){
      $(this).hide();
    $('#ajax-comment').html("<%= escape_javascript(render(:partial => '/articles/comment', collection: @article.comments.order("created_at DESC"))) %>");

  });
  });


</script>


 

app/views/comments/_form.html.erb
<div class="comment comment-box" id="comment-hide">
 <div class="user-photo">
 <%= link_to (image_tag current_author.author_pic.url(:small), :class=>"show-user-comment-pic"), author_profile_path(current_author.id) %>

 </div>
<div class="comment-body">
<%= form_for [ @article, @comment ], :remote =>"true" do |f|%>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
                <div class="input-group">
                  <div class="inputer">
                    <div class="input-wrapper">
               
                            <%= f.text_area :body, :placeholder=> "Join the discussion", :class=>"form-control js-auto-size", :rows=>"1", :required => "true", :id =>"write-comment" %>
                     
                    </div>
                  </div><!--.inputer-->
  <div class="field">
    
    <%= f.hidden_field :author_id, :value => current_author.id %>
  </div>
  <div class="field">
    
    <%= f.hidden_field :article_id, :value => @article_id %>
  </div>

                  <span class="input-group-btn">
                    <%= f.submit "Send", :class=>"btn btn-primary" %>
                  </span>
                </div><!--.input-group-->

              </div><!--.comment-body-->





<% end %>
  </div><!--.comment-->

app/views/comments/create.js.erb
$("#ajax-comment").html("<%= escape_javascript(render(:partial => '/articles/comment', collection: @article.comments.order("created_at DESC"))) %>");
$("#write-comment").val("");
$("#count").html("<%= @article.comments.size %>")

app/views/comments/destroy.js.erb
$("#ajax-comment").html("<%= escape_javascript(render(:partial => '/articles/comment', collection: @article.comments.order("created_at DESC"))) %>");
$("#count").html("<%= @article.comments.size %>")

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>
<%= render partial: 'form' %>

app/views/comments/edit.js.erb
$("#<%=@comment.id%>").html("<%= escape_javascript(render(:partial => '/comments/editform' )) %>");

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Author</th>
      <th>Article</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.author %></td>
        <td><%= comment.article %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

app/views/comments/update.js.erb
$("#ajax-comment").html("<%= escape_javascript(render(:partial => '/articles/comment', collection: @article.comments.order("created_at DESC"))) %>");
// $("#<%=@comment.id%>").find(".comment-abc").html("<%=@comment.body%>")
// $("#<%=@comment.id%>").html("");