config/routes.rb
Rails.application.routes.draw do
   get '/articles/autocomplete' => 'articles#autocomplete'

  resources :tags
 
  resources :articles do
   resources :comments
 end
  devise_for :authors, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root 'articles#index'
   get 'author_profile/:id' => 'articles#author_profile', as: :author_profile
   get '/name' => 'articles#name' ,as: :name

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence:true
  validates :body, presence:true, :length => { :minimum => 10 }
  belongs_to :author
  has_many :comments, :dependent => :destroy
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings, :dependent => :destroy

  has_many :blog_categories

  has_many :master_categories, :through => :blog_categories

  has_attached_file :image, styles: { large:"1215x600>" , medium: "600x450>", thumb: "45x45>", small: "200x112>" }, :default_url => "/assets/missing_article_image.jpg"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

searchable do
text :title, :boost => 5
  # text :name
    # integer :article_id
    # integer :master_category_ids, :multiple => true

     string :master_category_ids, :multiple => true, :references => 'MasterCategory' do

 master_categories.map(&:name)

      #  master_categories.map do |m|
      #   {:name=> m.name}
      # end
     
    end
# string :master_category_ids, :multiple => true, :references => 'Master_Category' do
#       master_categories.map do |m|
#         {:name=> m.name}
#       end
#     end
end


def tag_list
  self.tags.collect do |tag|
    tag.name
  end.join(", ")
end

def tag_list=(tags_string)
  tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
  new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  self.tags = new_or_found_tags
end



end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :check, only: [:edit]
  # layout :my_layout
  # GET /articles
  # GET /articles.json
  def index

    @masters=MasterCategory.all
    @blogs=BlogCategory.all

    # @articles =Article.all

    @search=Article.search do
    fulltext params[:search]
    paginate :page => 1, :per_page => 6
    end

    @search_author=Author.search do
    fulltext params[:search]
    paginate :page => 1, :per_page => 6
    end
    
    # @search_filter= Article.search do
      # fulltext params[:search]
      # with(:master_category_ids).all_of(params[:master_category_id]) unless params[:master_category_id].blank?     
   
    # end
    @search_filter= Article.search do |s| 
    s.with(:master_category_ids, params[:search]) 
    end
   # @search_filter= Article.search do
   #  fulltext params[:search]
   #  with(:master_category_ids).all_of(params[:master_category_id]) unless params[:master_category_id].blank?
   #  end

   

    # @ab =params[:ab]
     @articles= @search.results  
     @authors =@search_author.results

      @filters=@search_filter.results


#      respond_to do |format|
#       if @authors.present?
#          format.js   
#      end
# end

  end


  

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    @comment = Comment.new
    @comment.article_id = @article.id
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    # @author = Author.find(params[:author_id])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @author= Author.find(current_author.id)
    @article= Article.find(params[:id])
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
     
        # if params[:@abc].present?
        #     redirect_to articles_path(@articles)
        
        
        # else
        # respond_to do |format|
        #  format.js
        # end
        # end
  end

  def author_profile
       @author= Author.find(params[:id])    
  end


# def categories_properties
#     @article = Article.find(params[:article_id])
    
#     params[:category][:id].each do |category|
#       if !category.blank?
#         @placeCategory = Place_Category.new
#         @placeCategory.article_id = @article.id
#         @placeCategory.master_category_id = category
#         @placeCategory.save
#       end
#     end
#   end
# def my_layout
#   params[:action] == 'author_profile' ? 'application' : nil
# end

  def check
         @article = Article.find(params[:id])
      if current_author.id!=@article.author_id
         respond_to do |format|
         format.html { redirect_to articles_path, notice: 'You are not authorised.' }
         format.json { render :show, status: :ok, location: @article }
          end
     end
 end
 
def name
 
 if Author.where(:email => params[:email]).exists?
  @a=1
  end
 respond_to do |format|
  format.js
 
end
end

def autocomplete

  @title=Article.all
  @authorx=Author.all

   respond_to do |format|
    format.html
    format.json { render :json=>@title.to_json   }
    # format.json { render :json=>@authorx.to_json   }
end

end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :image, :author_id, :tag_list, :username, :name, :master_category_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_allarticles.html.erb
 <% @articles.each do |article| %>
    <div class="col-md-5 blank-a" style="padding-bottom: 10px;">
      <div class="card card-event">
        <div class="card-heading bg-image">
         <%=link_to (image_tag article.image.url(:medium), :style=>"    width: 100%; height: 180px;    position: relative;"), article_path(article.id)%>

         
       </div><!--.card-heading-->

       <div class="card-body" style="
       margin-top: 30px;
       background-color: white;
       height: 250px;
       padding-top: 30px;
       ">
       <div class="calendar" style="top:-22px;">
        <div class="month" style="    width: 74px;"><%= article.created_at.strftime("%B %-d")%></div>
        <div class="date"><%= article.created_at.strftime("%Y")%></div>
      </div><!--.calendar-->
      <h4><%=link_to article.title, article_path(article.id), :class=> "read-more" %></h4>

     
      <p> <%=  sanitize(article.body, tags: %w(p )).truncate(120, :separator => " ").html_safe%><%=link_to "Read More", article_path(article.id), :class=> "read-more"%></p>
    </div><!--.card-body-->

    
  </div><!--.card-->

</div><!--.col-md-6-->

<% end %>

app/views/articles/_authorarticles.html.erb
<% @authors.each do |a| %>
    <% a.articles.each do |b| %>



    <div class="col-md-5" style="padding-bottom: 10px;">
      <div class="card card-event">
        <div class="card-heading bg-image">
         <%=link_to (image_tag b.image.url(:medium), :style=>"    width: 100%; height: 180px;    position: relative;"), article_path(b.id)%>

         
       </div><!--.card-heading-->

       <div class="card-body" style="
       margin-top: 30px;
       background-color: white;
       height: 250px;
       padding-top: 30px;
       ">
       <div class="calendar" style="top:-22px;">
        <div class="month" style="    width: 74px;"><%= b.created_at.strftime("%B %-d")%></div>
        <div class="date"><%= b.created_at.strftime("%Y")%></div>
      </div><!--.calendar-->
      <h4><%=link_to b.title, article_path(b.id), :class=> "read-more" %></h4>

     
      <p> <%=  sanitize(b.body, tags: %w(p )).truncate(120, :separator => " ").html_safe%><%=link_to "Read More", article_path(b.id), :class=> "read-more"%></p>
    </div><!--.card-body-->

    
  </div><!--.card-->

</div><!--.col-md-6-->

<% end %>

<%end%>

app/views/articles/_comment.html.erb
<li class="comment-list-li" >
<div class="comment" id="<%=comment.id%>" style="    border-radius: 8px;
    padding-left: 20px;
    padding-right: 20px;
    padding-top: 30px;
    background-color: rgba(240, 240, 240, 0.46);
    padding-bottom: 5px;">
<div class="user-photo">
<%= link_to (image_tag comment.author.author_pic.url(:small), :class=>"show-user-comment-pic"), author_profile_path(comment.author_id) %>
</div>
<div class="comment comment-body">
<div class="user">
											<ul class="inline-list ">
												<li ><%= link_to comment.author.username, author_profile_path(comment.author_id), :class=>"dot-seperator read-more", :style=> "color:#2095F2;    font-size: 15px;"%></li>&nbsp;
												<li style="font-size:12px;color: rgba(0, 0, 0, 0.5);"><%= time_ago_in_words(comment.created_at) %> ago</li>
												 
 <%if author_signed_in?%>
            <%if current_author.id == comment.author_id %>

<div style="float:right">
  
         <%=link_to '<i class="fa fa-pencil fa-fw "></i>'.html_safe,  edit_article_comment_path(:article_id => comment.article.id, :id => comment.id), data: { "toggle" => "tooltip", "title" => "Edit", "placement" => "bottom"}, :remote=>"true", :class=>"edit-comment-btn" %></li>&emsp;
   
       <%= link_to '<i class="fa fa-trash-o fa-fw " style="color:#d9534f;"></i>'.html_safe, article_comment_path(:article_id => comment.article.id, :id => comment.id), method: :delete, data: { "toggle" => "tooltip", "title" => "Delete", "placement" => "bottom", confirm: "Delete the comment ?"}, :remote=> "true" %></li>
        </div>

          <%end%>

          <%end%>

											</ul>
										</div>
 <p class="comment-abc" style="text-align:justify;font-size: 16px;"><%= comment.body%></p>

</div>

</div>
</li>

	

   

											
	
												

											
										

app/views/articles/_filter.html.erb
<% @filters.each do |f| %>
    <div class="col-md-5 blank-a" style="padding-bottom: 10px;">
      <div class="card card-event">
        <div class="card-heading bg-image">
         <%=link_to (image_tag f.image.url(:medium), :style=>"    width: 100%; height: 180px;    position: relative;"), article_path(f.id)%>

         
       </div><!--.card-heading-->

       <div class="card-body" style="
       margin-top: 30px;
       background-color: white;
       height: 250px;
       padding-top: 30px;
       ">
       <div class="calendar" style="top:-22px;">
        <div class="month" style="    width: 74px;"><%= f.created_at.strftime("%B %-d")%></div>
        <div class="date"><%= f.created_at.strftime("%Y")%></div>
      </div><!--.calendar-->
      <h4><%=link_to f.title, article_path(f.id), :class=> "read-more" %></h4>

     
      <p> <%=  sanitize(f.body, tags: %w(p )).truncate(120, :separator => " ").html_safe%><%=link_to "Read More", article_path(f.id), :class=> "read-more"%></p>
    </div><!--.card-body-->

    
  </div><!--.card-->

</div><!--.col-md-6-->

<% end %>

app/views/articles/_form.html.erb
    <div class="row">
     

        <div class="panel" style="    padding: 20px;">
      
          <div class="panel-body">

<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


            <form action="#" class="form-horizontal">
              <div class="form-content">
               <div class="col-md-12" style="   padding: 15px;">
                <div class="form-group">
                  <label class="control-label col-md-2 col-md-offset-1">Title</label>
                  <div class="col-md-8">
                    <div class="inputer">
                      <div class="input-wrapper">
                       
                        <%= f.text_field :title, :class=>"form-control", :required => "true" %>
                      </div>
                    </div>
                  </div>
                </div><!--.form-group-->
                </div>


 <div class="col-md-12" style="  padding: 15px;">
                <div class="form-group">
                  <label class="control-label col-md-2 col-md-offset-1">Body</label>
                  <div class="col-md-8">
                   <%= f.text_area :body, :class=>"summernote summernote-default"%>
                  </div>
                </div><!--.form-group-->
                </div>
 

 <div class="col-md-12" style="    padding: 15px;">
                <div class="form-group">
                  <label class="control-label col-md-2 col-md-offset-1">Tag</label>
                  <div class="col-md-8">
                    <div class="inputer">
                      <div class="input-wrapper">
                       
                         <%= f.text_field :tag_list, :class=>"form-control"%>
                      </div>
                    </div>
                  </div>
                </div><!--.form-group-->
                </div>

            
              </div><!--.form-content-->

            
              <div class="col-md-12" style="   padding: 15px;">
               <div class="field">
                 <% if @article.image? %>
                <div class="col-md-2 col-md-offset-1">Article Image</div><!--.col-md-3-->
                <div class="col-md-8">
                 <div class="fileinput fileinput-new" data-provides="fileinput">
                   <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                    <%= image_tag @article.image.url(:medium)%>
                     </div>
                  <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;">
                   
                 </div>
                 <div>
                  <span class="btn btn-default btn-file">
                    <span class="fileinput" style="margin-bottom:0px;">Change</span>
                    <!-- <input type="file" na/me="..."> -->
                    <%= f.file_field :image %>
                  </span>
                  <a href="#" class="btn btn-default btn-file fileinput" data-dismiss="fileinput" style="margin-top:9px;">Remove</a>
                </div>
                </div>
                </div>
                <%else%>
                <div class="field">
                  <div class="col-md-2 col-md-offset-1">Article Image</div><!--.col-md-3-->
                  <div class="col-md-8">

                    <div class="fileinput fileinput-new" data-provides="fileinput">
                      <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">

                      </div>
                      <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                      <div>
                        <span class="btn btn-default btn-file">

                          <span class="fileinput-new">Select image</span>
                          <span class="fileinput-exists">Change</span>
                          <!-- <input type="file" name="..."> -->
                          <%= f.file_field :image %>
                        </span>
                        <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                      </div>
                    </div>

                  </div><!--.col-md-9-->    

                </div>
   <% end %>

              </div>
              </div>
           




<% if author_signed_in?%>
  <div class="field">
    
    <%= f.hidden_field :author_id, :value => current_author.id %>
  </div>
  <%end%>
 <div class="col-md-12" style="   padding: 15px;">
              <div class="form-buttons">
                <div class="row">
               <div class="col-md-1 col-md-offset-8 col-sm-3 col-xs-6 col-sm-offset-4">
                      
                <button class="btn btn-flat btn-default" onclick="goBack()" style="background-color: rgba(255, 0, 0, 0.68);     color: white;">Cancel</button>
                    </div>
                     <div class="col-md-1 col-md-offset-1 col-sm-3 col-xs-6">
                <%= f.submit "Submit", :class=>"btn btn-blue", :style=>"    margin-left: -20px;" %>
                  </div>
                </div>
              </div>
              </div>
            </form>

          </div><!--.panel-body-->
        </div><!--.panel-->

      </div><!--.col-md-12-->
    </div><!--.row-->

<script>
function goBack() {
    window.history.back();
}





</script>

 
 

 
  

<% end %>

app/views/articles/edit.html.erb
<h3 style="    padding: 20px;
    text-align: center;">Editing Article</h3>

<%= render 'form' %>

app/views/articles/index.js.erb
<%#if params[:@xyz].present?%>
$('#all-articles').html('<%= raw escape_javascript(render "/articles/allarticles") %>');
<%#else%>
$('#filter-value').html('<%= raw escape_javascript(render "/articles/filter") %>');
<%#end%>

app/views/articles/name.js.erb
<%if @a == 1%>
$("#same").show();

$('#sub').prop('disabled', true);

       $("#check").click(function(){
     $("#same").hide();
   });
   
   <%else%>
   
   $('#sub').prop('disabled', false);

   <%end%>

app/views/articles/new.html.erb
<h3 style="    padding: 20px;
    text-align: center;">New Article</h3>
<div>
<%= render 'form' %>
<!--asadfadf-->
</div>

app/views/articles/show.html.erb
<div class="content">

  <div class="page-header brown full-content parallax opacity-hero" style="height: 450px; overflow: hidden;    margin-top: 0px;
    margin-right: -80px; 
    margin-left: -80px;     margin-bottom: 16px;">
    <div >
    <%= image_tag @article.image.url(:large), :style=>" background-size: cover; width: 100%; height: 100%; position: absolute; left: 0; top: 0;" %>
    </div>

    <div class="row">
      <!--.col-->
       <!--  <div class="col-sm-6">
          <ol class="breadcrumb">
            <li><a href="#"><i class="ion-home"></i></a></li>
            <li><a href="#">Pages</a></li>
            <li><a href="#" class="active">Blog</a></li>
          </ol>
        </div> --><!--.col-->
      </div><!--.row-->

    </div><!--.page-header-->
     <%if author_signed_in?%>
            <%if current_author.id == @article.author_id %>
         <div style="float:right">
  
         <%=link_to '<i class="fa fa-pencil fa-fw fa-lg "></i>'.html_safe,  edit_article_path(@article), data: { "toggle" => "tooltip", "title" => "Edit", "placement" => "bottom"} %></li>&emsp;
   
       <%= link_to '<i class="fa fa-trash-o fa-fw fa-lg" style="color:#d9534f;"></i>'.html_safe, article_path(@article, :@abc=> true), method: :delete, data: { "toggle" => "tooltip", "title" => "Delete", "placement" => "bottom", confirm: "Delete the comment ?"}%></li>
        </div>
            <%end%>
            <%end%>
    <div class="row">
      <div class="col-md-12 col-xs-12">
        <h1 class="text-center margin-bottom-40" style="font-size: 34px; margin-top:20px; margin-bottom:30px!important; letter-spacing: 2px;font-weight: 400;
" ><%= @article.title %></h1>
      </div><!--.col-->
    </div><!--.row-->
  <!--   <p>
      <strong>Author:</strong>
      <%= @article.author.username %>
    </p> -->







      

<div class="row">
      <div class="col-md-12">

        <p style="text-align:justify;font-size: 18px;color: blue;    color: rgba(0, 0, 0, 0.87);
    font-weight: 300;"><%=  raw @article.body%></p>
                    <%if @article.tags.present?%>    
         
 <div class="row">
  <div style="float:right;     margin-top: 5px;">
  <% @article.tags.each do |tag| %>
     


          <ul class="inline-list" style="display:inline-block;">
            <li><span class="badge tag-name"><%=tag.name.upcase%></span></li>

          </ul>

     <!--.col-->
       <% end %>

      </div>
    </div><!--.row-->   
         
      
        <%end%>

      </div><!--.col-->
    </div><!--.row-->


<div class="row">
      <div class="col-md-12">
<p class="time"><span style="font-size: 16px;"><%= @article.created_at.strftime("%B %-d, %Y")%></span> <small style="color: #737373;     font-size: 15px;"> by <%=link_to @article.author.username, author_profile_path(@article.author_id), :class=>"read-more", :style=>"color: #2098F3;"%></small></p>
</div>
</div>

   
      <!--   <div class="row image-row margin-top-40 margin-bottom-40">

          <div class="col-md-6 col-md-offset-2" >
            <%= image_tag @article.image.url(:medium) %>
          </div>
        </div> -->

 





        <!-- <ul class="inline-list social-list">
          <li><a class="btn btn-facebook"><i class="ion-social-facebook"></i></a></li>
          <li><a class="btn btn-twitter"><i class="ion-social-twitter"></i></a></li>
          <li><a class="btn btn-googleplus"><i class="ion-social-googleplus"></i></a></li>
        </ul> -->

      </div><!--.col-->
    </div><!--.row-->

    <div class="full-content bg-white margin-top-40" style="margin-left: 0px;
    margin-right: 0px;    overflow-x: hidden;">
      <div class="row">
        <div class="col-md-8 col-md-offset-2" style="    padding: 30px;
    padding-top: 0px;">

          <h4 style="    font-size: 22px;">Comments(<span id="count"><%=@article.comments.size%></span>)</h4>

          <div class="comments">

          <%if author_signed_in?%>
            <%= render partial: 'comments/form' %>
            <%article_id=@article.id%>
            <%end%>
         <div id="ajax-comment">
            <%= render partial: 'articles/comment', collection: @article.comments.order("created_at DESC")%>
            </div>



          
           
           



          </div><!--.comments-->

        </div><!--.col-->
      </div><!--.row-->
<%x= @article.author.articles.size%>
<%if x>1 %>
    <div class="row" style="padding:30px;     margin-left: -10px;
    margin-right: -10px;">
 <p style="      padding-left: 10px;font-size: 22px;font-weight: 500;">Recommended articles from same author : </p>
    <% a=@article.id %>
   
        <% @article.author.articles.limit(4).each do |art|%>
          <% if a!=art.id %>

      <div class="col-md-4">







      <div class="card card-event">
          <div class="card-heading bg-image">
           <%=link_to (image_tag art.image.url(:medium), :style=>"    width: 100%;    position: relative;"), article_path(art.id), :style=>"    height: 300px;"%>
          </div><!--.card-heading-->

          <div class="card-body" style="    margin-top: 30px;
    background-color: white;        height: 215px;">
            <div class="calendar">
              <div class="month" style="    width: 68px;"><%= art.created_at.strftime("%B %-d")%></div>
              <div class="date"><%= art.created_at.strftime("%Y")%></div>
            </div><!--.calendar-->
            <h4 style="font-size: 20px;color: #7C9194;margin-top: 20px;"><%=link_to art.title, article_path(art.id), :class=> "read-more" %></h4>
            <p style="font-size: 15px; "><%=  sanitize(art.body, tags: %w(p )).truncate(120, :separator => " ").html_safe%><%=link_to "Read More", article_path(art.id), :class=> "read-more hover-read-more" ,:style=>"color: #9d9d9d;"%></p>
          </div><!--.card-body-->

    
        </div><!--.card-->

      </div><!--.col-md-4-->

      


   <%end%>
        <%end%>
    </div><!--.row-->
    <%else%>
    <%end%>
    </div><!--.full-content-->



  </div><!--.content-->